import { createSlice } from "@reduxjs/toolkit";
import userImg from "../../pages/Admin/Feedback/assets/images/user-img.svg";

const toolkitSlice = createSlice({
  name: "toolkit",
  initialState: {
    feedbackAllMessages: [
      {
        id: 1,
        imgUrl: userImg,
        fullName: "Ажар ....",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `Lorim ipsum .. . . . . . . . . I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 2,
        imgUrl: userImg,
        fullName: "Диана Диана",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 3,
        imgUrl: userImg,
        fullName: "Аселя",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 4,
        imgUrl: userImg,
        fullName: "Юлия",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 5,
        imgUrl: userImg,
        fullName: "Стефани",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 6,
        imgUrl: userImg,
        fullName: "Роуз",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 7,
        imgUrl: userImg,
        fullName: "Ажар Асылбаева",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 8,
        imgUrl: userImg,
        fullName: "Ажар Асылбаева",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 9,
        imgUrl: userImg,
        fullName: "Ажар Асылбаева",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 10,
        imgUrl: userImg,
        fullName: "Ажар Асылбаева",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 11,
        imgUrl: userImg,
        fullName: "Ажар Асылбаева",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
    ],
    feedbackReadMessages: [
      {
        id: 1,
        imgUrl: userImg,
        fullName: "Ажар ---",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `Good evening! How are you today? I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 2,
        imgUrl: userImg,
        fullName: "Диана Диана",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 3,
        imgUrl: userImg,
        fullName: "Аселя",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 4,
        imgUrl: userImg,
        fullName: "Юлия",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 5,
        imgUrl: userImg,
        fullName: "Стефани",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 6,
        imgUrl: userImg,
        fullName: "Роуз",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 7,
        imgUrl: userImg,
        fullName: "Ажар Асылбаева",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
    ],
    feedbackFavoriteMessages: [
      {
        id: 1,
        imgUrl: userImg,
        fullName: "Ажар !!!",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `Hey there! I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 2,
        imgUrl: userImg,
        fullName: "Диана Диана",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 3,
        imgUrl: userImg,
        fullName: "Аселя",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 4,
        imgUrl: userImg,
        fullName: "Юлия",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 5,
        imgUrl: userImg,
        fullName: "Стефани",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 6,
        imgUrl: userImg,
        fullName: "Роуз",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
      {
        id: 7,
        imgUrl: userImg,
        fullName: "Ажар Асылбаева",
        date: "02.03.2023",
        time: "9:38",
        email: "example@gmail.com",
        message: `I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
      },
    ],
    feedbackCurrentUser: {
      id: 1,
      imgUrl: userImg,
      fullName: "Ажар ....",
      date: "02.03.2023",
      time: "9:38",
      email: "example@gmail.com",
      message: `Lorim ipsum .. . . . . . . . . I am pleased to invite you all to our team building event that will be held next Friday, January 21st at 2 pm. The event will be held at the company's conference hall, we will have games`,
    },
    feedbackSearchValue: "",
  },
  reducers: {
    setFeedbackCurrentUser(state, action) {
      state.feedbackCurrentUser = action.payload;
    },
    setFeedbackSearchValue(state, action) {
      state.feedbackSearchValue = action.payload;
    },
  },
});

export default toolkitSlice.reducer;
export const { setFeedbackCurrentUser, setFeedbackSearchValue } =
  toolkitSlice.actions;
